UJM\ExoBundle\Entity\InteractionQCM:
    properties:
        scoreRightResponse:
            - UJM\ExoBundle\Validator\Constraints\isValidQCMGlobalMark: {message: "invalid_mark"}

        scoreFalseResponse:
            - UJM\ExoBundle\Validator\Constraints\isValidQCMGlobalMark: {message: "invalid_mark"}

UJM\ExoBundle\Entity\Hint:
    properties:
        penalty:
            - UJM\ExoBundle\Validator\Constraints\isValidMark: ~

UJM\ExoBundle\Entity\Choice:
    properties:
        weight:
            - UJM\ExoBundle\Validator\Constraints\isValidQCMMark: ~
            
UJM\ExoBundle\Entity\InteractionOpen:
    properties:
        scoreMaxLongResp:
            - UJM\ExoBundle\Validator\Constraints\isValidMark: ~
            
UJM\ExoBundle\Entity\WordResponse:
    properties:
        score:
            - UJM\ExoBundle\Validator\Constraints\isValidMark: ~
            
UJM\ExoBundle\Entity\Question:
    properties:
        category:
            - UJM\ExoBundle\Validator\Constraints\isNotEmpty: ~